# Generated by Django 4.2.6 on 2023-10-20 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0005_remove_workorder_quantity_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='workorder',
            name='status',
            field=models.CharField(choices=[('Scheduled', 'Scheduled'), ('In Progress', 'In Progress'), ('Completed', 'Completed'), ('On Hold', 'On Hold'), ('Rework', 'Rework'), ('Scrapped', 'Scrapped'), ('Lot Release', 'Lot Release')], default='Scheduled', max_length=25),
        ),
    ]
