# Generated by Django 4.2.6 on 2023-10-21 20:24

from django.db import migrations, models
import operations.models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0008_alter_material_request_type_alter_workorder_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='line_down_at',
            field=models.DateTimeField(default=operations.models.material.default_time_down),
        ),
    ]
