# Generated by Django 4.2.6 on 2023-10-22 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('htmx', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='element',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
