# Generated by Django 4.2.6 on 2023-10-22 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('htmx', '0003_alter_element_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('photo', models.ImageField(upload_to='')),
                ('url', models.URLField()),
            ],
        ),
    ]
