# Generated by Django 4.2.6 on 2023-11-02 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('htmx', '0004_resource'),
    ]

    operations = [
        migrations.AlterField(
            model_name='element',
            name='content',
            field=models.TextField(),
        ),
    ]
