# Generated by Django 4.2.6 on 2023-11-03 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('htmx', '0005_alter_element_content'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Element',
        ),
        migrations.DeleteModel(
            name='Resource',
        ),
    ]
