# Generated by Django 4.2.6 on 2023-10-20 01:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='catalog_material',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('material_name', models.CharField(max_length=255)),
                ('avg_per_each', models.DecimalField(decimal_places=6, max_digits=15)),
                ('unit_of_measure', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='catalog_number',
            fields=[
                ('catalog_number', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='department',
            fields=[
                ('id', models.CharField(max_length=25, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('icon', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=25)),
                ('department_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='operations.department')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='line',
            fields=[
                ('name', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('description', models.TextField()),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='operations.department')),
            ],
        ),
        migrations.CreateModel(
            name='workorder',
            fields=[
                ('workorder', models.CharField(max_length=25, primary_key=True, serialize=False)),
                ('quantity_start', models.IntegerField()),
                ('quantity_active', models.IntegerField()),
                ('lot_number', models.CharField(max_length=25)),
                ('priority', models.IntegerField()),
                ('scheduled_start', models.DateField()),
                ('actual_start', models.DateField()),
                ('due_date', models.DateField()),
                ('wj_printed', models.BooleanField(default=False)),
                ('br_printed', models.BooleanField(default=False)),
                ('labels_ordered', models.BooleanField(default=False)),
                ('labels_received', models.BooleanField(default=False)),
                ('catalog_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='operations.catalog_number')),
            ],
        ),
        migrations.CreateModel(
            name='schedule',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(max_length=25)),
                ('line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='operations.line')),
                ('workorder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='operations.workorder')),
            ],
        ),
        migrations.CreateModel(
            name='rejects',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('shift', models.CharField(max_length=1)),
                ('date', models.DateField()),
                ('quantity', models.IntegerField()),
                ('reason', models.TextField()),
                ('created', models.DateTimeField()),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='operations.employee')),
                ('line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='operations.line')),
                ('workorder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='operations.workorder')),
            ],
        ),
        migrations.CreateModel(
            name='output',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('shift', models.CharField(max_length=1)),
                ('date', models.DateField()),
                ('quantity', models.IntegerField()),
                ('comments', models.TextField()),
                ('created', models.DateTimeField()),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='operations.employee')),
                ('line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='operations.line')),
                ('workorder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='operations.workorder')),
            ],
        ),
        migrations.CreateModel(
            name='material',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('request_type', models.CharField(max_length=25)),
                ('quantity', models.IntegerField()),
                ('line_down_at', models.IntegerField()),
                ('comments', models.TextField()),
                ('delivery_status', models.CharField(max_length=25)),
                ('line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='operations.line')),
                ('part_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='operations.catalog_material')),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='operations.employee')),
                ('workorder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='operations.workorder')),
            ],
        ),
        migrations.CreateModel(
            name='line_reject',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('reason', models.CharField(max_length=25)),
                ('line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='operations.line')),
            ],
        ),
        migrations.CreateModel(
            name='line_goal',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('shift', models.CharField(max_length=1)),
                ('total_good', models.IntegerField()),
                ('total_downtime', models.IntegerField()),
                ('percent_reject', models.DecimalField(decimal_places=2, max_digits=5)),
                ('line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='operations.line')),
            ],
        ),
        migrations.CreateModel(
            name='line_downtime',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('reason', models.CharField(max_length=25)),
                ('line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='operations.line')),
            ],
        ),
        migrations.CreateModel(
            name='downtime',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('reason', models.TextField()),
                ('employee_end', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='downtime_end_set', to='operations.employee')),
                ('employee_start', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='downtime_start_set', to='operations.employee')),
                ('line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='operations.line')),
            ],
        ),
        migrations.AddField(
            model_name='catalog_material',
            name='catalog_number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='operations.catalog_number'),
        ),
    ]
