# Generated by Django 4.2.6 on 2023-10-23 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0009_alter_material_line_down_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='request_type',
            field=models.CharField(choices=[('New Lot', 'New Lot'), ('New Rack', 'New Rack'), ('Replacement Rack', 'Replacement Rack'), ('Project Lot', 'Project Lot')], max_length=25),
        ),
    ]
