# Generated by Django 4.2.6 on 2023-10-25 20:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0010_alter_material_request_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='output',
            name='created',
        ),
        migrations.RemoveField(
            model_name='output',
            name='quantity',
        ),
        migrations.AddField(
            model_name='output',
            name='end_unit',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(9999)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='output',
            name='start_unit',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(9999)]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='output',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
