# Generated by Django 4.2.6 on 2023-10-25 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0011_remove_output_created_remove_output_quantity_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='rejects',
            new_name='reject',
        ),
        migrations.AddField(
            model_name='downtime',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='line_goal',
            name='shift',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E')], default='A', max_length=1),
        ),
    ]
