# Generated by Django 4.2.6 on 2023-10-25 23:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0012_rename_rejects_reject_downtime_comment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='downtime',
            name='employee_end',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='downtime_end_set', to='operations.employee'),
        ),
        migrations.AlterField(
            model_name='downtime',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='status',
            field=models.CharField(choices=[('Released', 'Released'), ('In Progress', 'In Progress'), ('On Hold', 'On Hold'), ('Rework', 'Rework'), ('Lot Release', 'Lot Release'), ('Scrapped', 'Scrapped'), ('Completed', 'Completed')], default='Scheduled', max_length=25),
        ),
    ]
