# Generated by Django 4.2.6 on 2023-10-25 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0013_alter_downtime_employee_end_alter_downtime_end_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='downtime',
            name='reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
