# Generated by Django 4.2.6 on 2023-11-08 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0014_alter_downtime_reason'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reject',
            name='created',
        ),
        migrations.AlterField(
            model_name='reject',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
