# Generated by Django 4.2.6 on 2023-11-08 08:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0015_remove_reject_created_alter_reject_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='output',
            name='quality',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='output',
            name='safety',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='schedule',
            name='status',
            field=models.CharField(choices=[('On-Deck', 'On-Deck'), ('In-Process', 'In-Process'), ('Completed', 'Completed')], default='On-Deck', max_length=25),
        ),
    ]
