# Generated by Django 4.2.6 on 2023-10-20 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='catalog_material',
            options={'verbose_name': 'Catalog Material'},
        ),
        migrations.AlterModelOptions(
            name='catalog_number',
            options={'verbose_name': 'Catalog Number'},
        ),
        migrations.AlterModelOptions(
            name='line_downtime',
            options={'verbose_name': 'Line Downtime'},
        ),
        migrations.AlterModelOptions(
            name='line_goal',
            options={'ordering': ['line', 'shift'], 'verbose_name': 'Line Goal'},
        ),
        migrations.AlterModelOptions(
            name='line_reject',
            options={'verbose_name': 'Line Reject'},
        ),
        migrations.RenameField(
            model_name='catalog_material',
            old_name='avg_per_each',
            new_name='avg_per_unit',
        ),
        migrations.AlterField(
            model_name='line',
            name='name',
            field=models.CharField(help_text='Enter the name of the line. This field must be unique.', max_length=255, primary_key=True, serialize=False),
        ),
    ]
