# Generated by Django 4.2.6 on 2023-10-20 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0002_alter_catalog_material_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workorder',
            name='actual_start',
            field=models.DateField(help_text='The actual start date of the workorder.', null=True),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='quantity_active',
            field=models.IntegerField(help_text='Living quantity of units as it progresses through the lines.', null=True),
        ),
    ]
